library(spatstat)
bei
plot(bei)
plot(bei, pch=15)
plot(bei, pch=15, cex=.5)
bei.extra
plot(bei.extra)
el <- bei.extra$elev
plot(el)
el <- bei.extra[[1]]
dmap <- density(bei)
plot(dmap)
points(bei)

plot(el)
points(bei)

gr <- bei.extra[[2]]
plot(gr)
points(bei)
par(mfrow=c(1,2)) 
plot(dmap)
plot(el)
par(mfrow=c(2,1)) 
plot(dmap)
plot(el)
dev.off()
cl <- colorRampPalette(c("green", "red", "blue"))
plot(dmap, col=cl)
cl <- colorRampPalette(c("green", "red", "blue"))(100)
plot(dmap, col=cl)
cln <- colorRampPalette(c("chartreuse1", "brown2", "cyan", "lightblue"))
plot(dmap, col=cln(100))
dev.off()
par(mfrow=c(1,2)) 
plot(dmap, col=cl)
plot(dmap, col=cln)
ppm(bei ~ gr)
fit <- ppm(bei ~ gr)
summary(fit)
plot(predict(fit))
points(bei)
diagnose(fit)
